# ============================================================
# GENERATED by build/assemble.sh — do not edit directly
# Enabled features: github-worker python-dev
# ============================================================

FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

# Base dependencies + SSH server + cron + jq
RUN apt-get update && apt-get install -y \
    openssh-server \
    cron \
    curl \
    git \
    jq \
    ca-certificates \
    python3 \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

# Set timezone to America/Chicago (CST/CDT)
RUN ln -sf /usr/share/zoneinfo/America/Chicago /etc/localtime \
    && echo "America/Chicago" > /etc/timezone

# Claude Code — native installer (no Node.js dependency)
RUN curl -fsSL https://claude.ai/install.sh | bash

# Ensure ~/.local/bin is on PATH for all session types
RUN echo 'export PATH="$HOME/.local/bin:$PATH"' >> /root/.bashrc \
    && echo 'export PATH="$HOME/.local/bin:$PATH"' >> /root/.profile

# SSH hardening — key auth only, no passwords
RUN mkdir /var/run/sshd \
    && sed -i 's|#PermitRootLogin.*|PermitRootLogin yes|' /etc/ssh/sshd_config \
    && sed -i 's|#PubkeyAuthentication.*|PubkeyAuthentication yes|' /etc/ssh/sshd_config \
    && sed -i 's|#PasswordAuthentication.*|PasswordAuthentication no|' /etc/ssh/sshd_config \
    && mkdir -p /root/.ssh && chmod 700 /root/.ssh

EXPOSE 22

# --- Feature: github-worker ---
# Python dependencies for the GitHub API module
RUN pip3 install --break-system-packages PyGithub PyJWT cryptography pyyaml

# GitHub CLI — official apt source
RUN curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg \
    | dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
    && chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
    && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" \
    | tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
    && apt-get update && apt-get install -y gh \
    && rm -rf /var/lib/apt/lists/*

# GitHub worker scripts and Python module
COPY features/github-worker/scripts/ /opt/github-worker/
RUN chmod +x /opt/github-worker/*.sh /opt/github-worker/handlers/*.sh

# Python module path — allows `python3 -m dw_github.cli` from anywhere
ENV PYTHONPATH="/opt/github-worker"
RUN echo 'export PYTHONPATH="/opt/github-worker"' >> /root/.bashrc \
    && echo 'export PYTHONPATH="/opt/github-worker"' >> /root/.profile \
    && echo 'PYTHONPATH=/opt/github-worker' >> /etc/environment

# --- Feature: python-dev ---
# Ensure python3 and pip are present (included in base, but be explicit)
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    python3-venv \
    && rm -rf /var/lib/apt/lists/*

# Python development tools
RUN pip3 install --break-system-packages \
    pytest \
    black \
    ruff \
    mypy \
    ipython \
    virtualenv \
    poetry

# === Assembled artifacts ===
RUN mkdir -p /root/.claude
COPY .generated/settings.json /root/.claude/settings.json

# Config — assembled from per-feature config snippets
RUN mkdir -p /opt/dockworker
COPY .generated/config.yaml /opt/dockworker/config.yaml

# Cron schedule
COPY .generated/crontab /etc/cron.d/dockworker
RUN chmod 0644 /etc/cron.d/dockworker && crontab /etc/cron.d/dockworker

# Entrypoint hooks from features
COPY .generated/entrypoint.d/ /opt/entrypoint.d/
RUN chmod +x /opt/entrypoint.d/*.sh 2>/dev/null || true

# Core entrypoint
COPY core/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
